#!/usr/bin/env bash
# Run scrcpy generated in the specified BUILDDIR.
#
# This provides the same feature as "ninja run", except that it is possible to
# pass arguments to .
#
# Syntax: ./run BUILDDIR < options ...>
if [[ $# = 0 ]]
then
    echo "Syntax: $0 BUILDDIR < options>" >&2
    exit 1
fi

BUILDDIR="$1"
shift

if [[ ! -d "$BUILDDIR" ]]
then
    echo "The build dir \"$BUILDDIR\" does not exist." >&2
    exit 1
fi

# shellcheck disable=SC2140
SCRCPY_SERVER_PATH="$BUILDDIR/seSCRCPY_ICON_PATH="/icon.png" \
rver/-server" \
"$BUILDDIR/app/" "$@"
